### ISSUE TITLE
Add gatsby-source-filesystem so mdx files can be accessed in graphql layer

### ISSUE THREAD

**Issue by lannonbr** [ChristopherBiscardi/gatsby-starter-mdx-basic#1]
As described in the docs for [programatically creating pages](https://gatsby-mdx.netlify.com/guides/programmatically-creating-pages), mdx files can be exposed in the graphql layer through `allMdx` or `mdx` by adding an entry to `gatsby-source-filesystem`.

I think it would be a good addition to add this so by default when you pull down the starter with `gatsby new`, you could automatically get the content through a graphql query.

**Comment by ChristopherBiscardi** [comment]
@lannonbr hmm, yeah. This was originally supposed to be an "as basic as possible" example but perhaps that would still be useful. Would be happy to accept a PR for this.
