### ISSUE TITLE
Cannot run new gatsby-starter-mdx-basic site

### ISSUE THREAD

**Issue by aheintz** [ChristopherBiscardi/gatsby-starter-mdx-basic#13]
I'm trying to run the generated site, but I get an error. I do a `gatsby new ...` and then `yarn && yarn develop`.

The error that follows is:
````
 ERROR #98123  WEBPACK

Generating development JavaScript bundle failed

~/docsite/src/pages/page-2.mdx: pragma and pragmaFrag cannot be set when runtime is automatic.
> 1 | import * as React from 'react'
    | ^
  2 |   /* @jsx mdx */
  3 | import { mdx } from '@mdx-js/react';
  4 | /* @jsx mdx */

File: src/pages/page-2.mdx

failed Building development bundle - 5.771s
````

Running `gatsby-cli 2.12.108` and `yarn 1.22.10` on Mac OS X 10.15.6

**Comment by ChristopherBiscardi** [comment]
looks like gatsby changed something with respect to the runtime/pragma usage. You should file a bug there as I don't work on gatsby any more and haven't for a long time.

My guess is that their newest dependencies would work but I really don't know.
