### ISSUE TITLE
Switch to gatsby-plugin-mdx?

### ISSUE THREAD

**Issue by karlhorky** [ChristopherBiscardi/gatsby-starter-mdx-basic#5]
Should this starter use `gatsby-plugin-mdx` instead of `gatsby-mdx`?

Confusingly, in [the Gatsby MDX docs](https://github.com/gatsbyjs/gatsby/blob/0f1cbedb3ef24cfcf8337b40ae0c0b12972a0f7b/docs/docs/mdx/getting-started.md), if you use this starter (in the **Quick Start** section) instead of following the **Add MDX to an existing Gatsby site**, you'll get `gatsby-mdx` instead of the newer `gatsby-plugin-mdx`...

**Comment by ChristopherBiscardi** [comment]
swapped, thanks.

**Comment by karlhorky** [comment]
Great, thanks to you as well!
