### ISSUE TITLE
Layout imports are confusing

### ISSUE THREAD

**Issue by mzedeler** [ChristopherBiscardi/gatsby-starter-mdx-basic#8]
AFAIK, the following lines are not required and were just a source of confusion for me:

https://github.com/ChristopherBiscardi/gatsby-starter-mdx-basic/blame/master/src/pages/index.mdx#L3
https://github.com/ChristopherBiscardi/gatsby-starter-mdx-basic/blame/master/src/pages/page-2.mdx#L2

I don't mind providing a PR removing them.

**Comment by tubbo** [comment]
removing them seems to have no effect, i say go for it.

**Comment by mzedeler** [comment]
Fixed in https://github.com/ChristopherBiscardi/gatsby-starter-mdx-basic/pull/11

**Comment by ChristopherBiscardi** [comment]
hey, I don't maintain this project anymore as I don't work with gatsby anymore. Thanks for the Issue, but I'm going to archive the project so other people aren't misled into thinking this is active.
