### ISSUE TITLE
Specific case where children components are not rendering

### ISSUE THREAD

**Issue by helmutgranda** [ChristopherBiscardi/gatsby-starter-mdx-basic#9]
Using children components and `renderToStaticMarkup` not rendering contents.

I put together a project so you can see the work in action:

https://codesandbox.io/s/gatsby-starter-mdx-basic-21mif

As you can see I have two components and the child component does not display the markup:

index.mdx
```js
<ShowHtml>
  <Test />
</ShowHtml>
```

If the component source code is all in one page, the component is rendered as expected. It seems to be only when the components are broken down into their individual folders:

https://codesandbox.io/s/empty-leftpad-5vomw

Any guidance would be greatly appreciated.

**Comment by ChristopherBiscardi** [comment]
hey, I don't maintain this project anymore as I don't work with gatsby anymore. Thanks for the Issue, but I'm going to archive the project so other people aren't misled into thinking this is active.
